name: Update events.json automatically

on:
  schedule:
    - cron: '0 * * * *'   # co godzinę
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Scrape and save events to JSON
        run: python save_events_to_json.py
      - name: Commit and push events.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "Auto-update events.json [ci skip]" || echo "No changes"
          git push